variables:
  BUILD_IMAGE: $CI_REGISTRY_IMAGE/dafny-ba

stages:
  - prebuild
  - build

build_docker:
  stage: prebuild
  image: docker:latest
  only:
    refs:
      - master
    changes:
      - Dockerfile
      - .gitlab-ci.yml
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --tag $BUILD_IMAGE:latest - < Dockerfile
    - docker push $BUILD_IMAGE:latest

build_pdf:
  stage: build
  image: $BUILD_IMAGE:latest
  artifacts:
    paths:
      - main.pdf
  script:
    - latexmk -pdf main.tex
    - makeglossaries main
    - latexmk -pdf main.tex
